//POSTS TYPES
export const GET_POST="GET_POST"
export const GET_POSTS="GET_POSTS"
export const GET_POSTS_BY_CATEGORY="GET_POSTS_BY_CATEGORY"
export const ADD_POST="ADD_POST"
export const EDIT_POST="EDIT_POST"
export const UPVOTE_POST="UPVOTE_POST"
export const DOWNVOTE_POST="DOWNVOTE_POST"
export const DELETE_POST="DELETE_POST"
export const SORT_POSTS="SORT_POSTS"

//COMMENT TYPES
export const GET_COMMENTS="GET_COMMENTS"
export const ADD_COMMENTS="ADD_COMMENTS"
export const EDIT_COMMENTS="EDIT_COMMENTS"
export const UPVOTE_COMMENT="UPVOTE_COMMENT"
export const DOWNVOTE_COMMENT="DOWNVOTE_COMMENT"
export const DELETE_COMMENT="DELETE_COMMENT"

//SORT TYPES
export const SET_FILTER="SET_FILTER"

//REDUX-PERSIST TYPES
export const REHYDRATE = "persist/REHYDRATE"
